// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zahidtvknzaxsywatrxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphaGlkdHZrbnpheHN5d2F0cnhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTYyNDMsImV4cCI6MjA2MjM3MjI0M30.Y9yyD0J7LoiZ7lb31nasPByGP6nJpk7mz_R9bEXJOBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);